### ISSUE TITLE
Widgets are reorganised not as reqested

### ISSUE THREAD

**Issue by MindGas** [campai-bv/autotask-dashboards-os#14]
After reorganising widgets and saving them, they are reorginised. In version 1.2 they staid the way they where reorganised.

**Comment by coencoppens** [comment]
@mind3m The reason they don't stay organized seems like a caching issue. It's probably because you're missing the Cache config in your bootstrap:

``` php
/**
 * Enables the models to use caching.
 */
Cache::config( '1_hour', array(
        'engine' => 'File'
    ,   'duration' => '+1 hours'
    ,   'path' => CACHE
    ,   'prefix' => 'cake_1_hour_'
));
```

After adding that, go to the edit screen of your dashboard and don't change anything, just hit the save button. Then go back to your dashboard and reorganize it.

Does that solve the problem?

**Comment by MindGas** [comment]
Thanks for pointer indeed it was to do with caching. I never knew why line <code>Configure::write('Cache.check', true);</code> in core.php needed to be un-commented. It gave some issues at the beginning of upgrade and then I didn't spot difference when commented or un-commented. It works now, but it requires after reorganising go to edit and save. At the end it work and it mater most.

**Comment by coencoppens** [comment]
Good to hear!
