### ISSUE TITLE
Undefined property: stdClass::$Priority

### ISSUE THREAD

**Issue by rgransier** [campai-bv/autotask-dashboards-os#16]
Guys,

I discovered some errors in the cronjob.log file:
2013-09-04 13:40:52 Cronjob: Failed: we've encountered some errors while running the import script.
Above this line it is full with many tickets, comments, etc. from Autotask (to many to display here)

When I check the debug.log, it says:
2013-09-04 13:35:42 Notice: Undefined property: stdClass::$Priority in [/var/www/app/Plugin/Autotask/Console/Command/ImportFromAutotaskShell.php, line 350]

Don't know if this is related to the SQL import bug with the single quote character, if it is, please let me know and I await your solution.

Thanks,
Roger

**Comment by jarrodmast** [comment]
This sounds like a bug - i'm guessing you have some or several tickets where the priority field is completely undefined/unset/empty?
I'm not sure if this is actually possible since priority is a required field? But I know in the 1.4 code @coencoppens has changed the ticket save to use safe sql and set some defaults where the tickets results may have null values - this hasn't been done for ticket->priority though - see https://github.com/coencoppens/autotask-dashboards/blob/1.4.0/Console/Command/ImportFromAutotaskShell.php#L391

To double check your data, run a ticket search in autotask - select all ticket statuses other than ''Complete'' and sort them by the ''Priority'' column - wondering if you have tickets created with an empty/unset priority?

**Comment by rgransier** [comment]
thanks for the reply; I checked all tickets and 2 of them appeared to have a '0' priority. I edited these to a default normal prio and will check the logging upcoming days....
